name: Audit Project Cards

on:
  schedule:
    - cron: '0 13 * * 1-5' # Runs at 1 PM UTC every weekday (Monday-Friday)
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  audit_cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install script dependencies
        run: npm install
        working-directory: ./.github/scripts

      - name: Run audit script
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/audit-project-cards.js');
            // We can't directly run the file, but we can require and execute it.
            // This is a simple way to keep using github-script's context.
            // However, a more standard approach would be to use `run: node ...`
            // Let's stick with the `require` approach for simplicity here.
            // This script is self-executing, so requiring it should run it.
            // Note: This pattern might not be standard. A better way is shown below.

      # The above step is a bit of a hack. Let's do it the proper node way.
      # Please use this step instead of the one above.
      - name: Run audit script (Standard Node.js method)
        run: node ./.github/scripts/audit-project-cards.js
        env:
          # Pass inputs to the script as environment variables, which the script reads via core.getInput
          INPUT_TOKEN: ${{ secrets.Project_bot_issues }}
          INPUT_PROJECT-ID: "PVT_kwHOBwWtRc4A6wWB"
          INPUT_REPO-OWNER: ${{ github.repository_owner }}
          INPUT_REPO-NAME: ${{ github.event.repository.name || github.repository_owner }}
          INPUT_AUDIT-ISSUE-NUMBER: ${{ '1' }}
          INPUT_REQUIRED-FIELDS: "Estimate,QPP Objective,Priority,Sprint"