name: Add issues to project on creation

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to project + label + status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.Project_bot_issues }}
          script: |
            const projectId = 'PVT_kwHOBwWtRc4A6wWB'
            const label = 'needs triage'

            // Step 1: Add label to issue
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [label]
            })

            // Step 2: Get issue node ID
            const issueId = (await github.graphql(`
              query {
                repository(owner: "${context.repo.owner}", name: "${context.repo.repo}") {
                  issue(number: ${context.issue.number}) {
                    id
                  }
                }
              }
            `)).repository.issue.id;

            // Step 3: Add issue to project and get itemId
            const addItemResponse = await github.graphql(`
              mutation {
                addProjectV2ItemById(input: {
                  projectId: "${projectId}",
                  contentId: "${issueId}"
                }) {
                  item {
                    id
                  }
                }
              }
            `);
            const itemId = addItemResponse.addProjectV2ItemById.item.id;

            // Step 4: Set field values (you must replace these with real IDs)
            const fieldUpdates = [
              {
                fieldId: "PVTFIELD_STATUS", // e.g. "Status"
                value: { singleSelectOptionId: "OPTION_BACKLOG" }
              },
              {
                fieldId: "PVTFIELD_PRIORITY", // e.g. "Priority"
                value: { singleSelectOptionId: "OPTION_MEDIUM" }
              },
              {
                fieldId: "PVTFIELD_TYPE", // e.g. "Type"
                value: { singleSelectOptionId: "OPTION_BUG" }
              }
            ];

            for (const { fieldId, value } of fieldUpdates) {
              await github.graphql(`
                mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: ProjectV2FieldValue!) {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: $projectId,
                    itemId: $itemId,
                    fieldId: $fieldId,
                    value: $value
                  }) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `, {
                projectId,
                itemId,
                fieldId,
                value
              });
            }
