name: Add issues to project on creation

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to project + label + status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.Project_bot_issues }}
          script: |
            const projectId = '10'
            const label = 'needs triage'

            // Add label to issue
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [label]
            })

            // Add issue to project (GraphQL)
            const issueId = (await github.graphql(`
              query {
                repository(owner: "${context.repo.owner}", name: "${context.repo.repo}") {
                  issue(number: ${context.issue.number}) {
                    id
                  }
                }
              }
            `)).repository.issue.id;

            await github.graphql(`
              mutation {
                addProjectV2ItemById(input: {
                  projectId: "${projectId}"
                  contentId: "${issueId}"
                }) {
                  item {
                    id
                  }
                }
              }
            `);
