name: Weekly Issue Status Report

on:
  schedule:
    - cron: '0 8 * * 1' # Runs at 8 AM UTC every Monday
  workflow_dispatch: # Allows manual triggering

jobs:
  generate_report:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.Project_bot_issues }} # Your PAT with repo and project scopes
      PROJECT_ID: "PVT_kwHOBwWtRc4A6wWB" # e.g., PVT_kwHOBwWtRc4A6wWB
      STATUS_FIELD_NAME: ${{ vars.STATUS_FIELD_NAME || 'Status' }} # Project's status field name, fallback to 'Status'
      TARGET_REPO_OWNER: ${{ github.repository_owner }} # Assumes running in the same repo, or set explicitly
      TARGET_REPO_NAME: ${{ github.event.repository.name || github.repository_owner }} # Assumes running in same repo, or set explicitly
      REPORT_ISSUE_ASSIGNEE: ${{ vars.REPORT_ISSUE_ASSIGNEE || '' }}

    steps:
      - name: Calculate Dates
        id: dates
        run: |
          echo "CURRENT_DATE=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "ONE_WEEK_AGO_ISO=$(date -u -d '7 days ago' +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "ONE_WEEK_AGO_DATE=$(date -u -d '7 days ago' +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Generate Report Content
        id: report_content
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.GH_TOKEN }}
          script: |
            // Access pre-configured Octokit via the 'github' global
            // const { Octokit } = require("@octokit/rest"); // DELETE THIS LINE
            // const octokit = new Octokit({ auth: process.env.GH_TOKEN }); // DELETE THIS LINE

            const projectId = process.env.PROJECT_ID;
            const statusFieldName = process.env.STATUS_FIELD_NAME;
            const owner = process.env.TARGET_REPO_OWNER;
            const repo = process.env.TARGET_REPO_NAME;
            const oneWeekAgoISO = "${{ steps.dates.outputs.ONE_WEEK_AGO_ISO }}";
            const currentDate = "${{ steps.dates.outputs.CURRENT_DATE }}"; // Get current date for report title
            
            let reportMarkdown = `## Issue Status Report for Week Ending ${currentDate}\n\n`;
            reportMarkdown += `Report generated from ${oneWeekAgoISO} to ${currentDate} UTC.\n\n`;

            // To access core functions like core.setFailed if needed
            const core = require('@actions/core'); 

            // --- 1. Project Item Activity (Items updated in the project this week) ---
            reportMarkdown += `### Project Items Activity (Project ID: ${projectId})\n`; // Using Project ID for clarity
            reportMarkdown += `_(Items whose project card was updated in the last week, showing current status from field "${statusFieldName}")_\n\n`;
            
            try {
              let projectItems = [];
              let hasNextPageItems = true;
              let endCursorItems = null;

              while(hasNextPageItems) {
                const projectQuery = `
                  query($projectId: ID!, $cursor: String) {
                    node(id: $projectId) {
                      ... on ProjectV2 {
                        items(first: 100, after: $cursor, orderBy: {field: UPDATED_AT, direction: DESC}) {
                          pageInfo {
                            hasNextPage
                            endCursor
                          }
                          nodes {
                            id
                            updatedAt
                            content {
                              ... on Issue { id number title url }
                              ... on PullRequest { id number title url }
                            }
                            fieldValueByName(name: "${statusFieldName}") {
                              ... on ProjectV2ItemFieldSingleSelectValue { name optionId }
                              // Add other field types if your status is not single-select
                              // ... on ProjectV2ItemFieldTextValue { text }
                            }
                          }
                        }
                      }
                    }
                  }`;
                const projectResult = await github.graphql(projectQuery, { projectId: projectId, cursor: endCursorItems });
                
                if (projectResult.node && projectResult.node.items) {
                  projectItems = projectItems.concat(projectResult.node.items.nodes);
                  hasNextPageItems = projectResult.node.items.pageInfo.hasNextPage;
                  endCursorItems = projectResult.node.items.pageInfo.endCursor;

                  // Stop fetching if the last fetched item is already older than our window
                  if (projectResult.node.items.nodes.length > 0) {
                    const lastItem = projectResult.node.items.nodes[projectResult.node.items.nodes.length - 1];
                    if (new Date(lastItem.updatedAt) < new Date(oneWeekAgoISO)) {
                       // If the oldest item on this page is older than our period,
                       // and items are ordered by UPDATED_AT DESC, we might not need to continue if hasNextPage is true.
                       // However, the main filter below will correctly select only recent items.
                    }
                  }
                } else {
                  hasNextPageItems = false; // Should not happen if projectResult.node is valid
                }
              }
              
              const recentProjectItems = projectItems.filter(item => item && item.content && new Date(item.updatedAt) >= new Date(oneWeekAgoISO));
              if (recentProjectItems.length > 0) {
                for (const item of recentProjectItems) {
                  const statusValue = item.fieldValueByName ? (item.fieldValueByName.name || 'N/A') : `N/A (Field '${statusFieldName}' not found or not single-select)`;
                  reportMarkdown += `* [#${item.content.number} ${item.content.title}](${item.content.url}) - Current Project Status: **${statusValue}** (Project item updated: ${new Date(item.updatedAt).toISOString().split('T')[0]})\n`;
                }
              } else {
                reportMarkdown += "* No project items were updated this week (or no items found).\n";
              }
            } catch (error) {
              console.error("Error fetching project items:", error.message);
              core.warning(`Error fetching project items: ${error.message}`); // Use core.warning or core.error
              reportMarkdown += `* Error fetching project item activity: ${error.message}\n`;
            }
            reportMarkdown += "\n";

            // --- 2. Issue State Changes (Closed/Reopened) ---
            reportMarkdown += `### Issues Closed or Reopened This Week (Repo: ${owner}/${repo})\n\n`;
            try {
              // Use the pre-authenticated 'github.rest' and 'github.paginate'
              const eventsPaginator = github.paginate.iterator(github.rest.issues.listEventsForRepo, {
                owner: owner,
                repo: repo,
                per_page: 100,
                since: oneWeekAgoISO // Filter events since one week ago
              });

              let foundEvents = [];
              for await (const { data: eventsPage } of eventsPaginator) { // Renamed 'events' to 'eventsPage' to avoid conflict
                for (const event of eventsPage) {
                  // 'since' in API call should handle this, but as a safeguard:
                  if (new Date(event.created_at) < new Date(oneWeekAgoISO)) continue;

                  if (event.event === 'closed' || event.event === 'reopened') {
                    if (!event.issue) continue; // Skip if no issue context

                    foundEvents.push({
                      number: event.issue.number,
                      title: event.issue.title || `Issue #${event.issue.number}`,
                      url: event.issue.html_url,
                      action: event.event,
                      date: event.created_at
                    });
                  }
                }
              }
              
              if (foundEvents.length > 0) {
                 // Sort by date for clarity (newest first)
                foundEvents.sort((a,b) => new Date(b.date) - new Date(a.date));
                for (const change of foundEvents) {
                  reportMarkdown += `* [#${change.number} ${change.title}](${change.url}) - **${change.action.charAt(0).toUpperCase() + change.action.slice(1)}** on ${new Date(change.date).toISOString().split('T')[0]}\n`;
                }
              } else {
                reportMarkdown += "* No issues were closed or reopened this week.\n";
              }
            } catch (error) {
              console.error("Error fetching issue events:", error.message);
              core.warning(`Error fetching issue events: ${error.message}`);
              reportMarkdown += `* Error fetching issue close/reopen events: ${error.message}\n`;
            }
            reportMarkdown += "\n";
            
            return reportMarkdown;

      - name: Write report to temporary file
        id: write_file # Give this step an id
        run: |
          echo "${{ steps.report_content.outputs.result }}" > weekly_report.md
          echo "filepath=weekly_report.md" >> $GITHUB_OUTPUT # Output the filepath

      - name: Create Report Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ env.GH_TOKEN }}
          title: "Weekly Issue Status Report - Week of ${{ steps.dates.outputs.ONE_WEEK_AGO_DATE }}"
          content-filepath: ${{ steps.write_file.outputs.filepath }} # Use the filepath from the previous step
          # body: ${{ steps.report_content.outputs.result }} <--- REMOVE THIS LINE
          labels: report, automation
          assignees: ${{ env.REPORT_ISSUE_ASSIGNEE }}